name: app
description: Your project description

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  logger: ^1.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  shared_preferences: ^2.1.1
  intl: ^0.18.0
  flutter_secure_storage: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
